app = "sendvpn-backend-gfyfeciw"
primary_region = "sjc"

[build]

[env]
PORT = "8080"
BOT_USERNAME = "jutsiaibot"
BOT_TOKEN = "8617108727:AAFA9A3QaR9hmAzLsrtqW6A74A6VhpCEubQ"
SESSION_SECRET = "sendvpn-prod-2026-04-30-secret-XK39fmLp"
INTERNAL_API_KEY = "sendvpn-internal-prod-2026-Tt7Lp9Qr"
SUB_BASE = "https://sub.jutsovpn.online"
DATA_DIR = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1

[[vm]]
size = "shared-cpu-1x"
memory = "1gb"
cpu_kind = "shared"
cpus = 1
